### PR TITLE
Images added

### PR DESCRIPTION
**Pull request by birajkarmakar**

### CODE REVIEW

**Comment by kushaldas** [comment]
Where is the source ?

**Comment by rtnpro** [comment]
img_20131226_000545
I was thinking of something like ^^

**Comment by rtnpro** [comment]
@kushaldas @sayanchowdhury @darkowlzz please comment :)

**Comment by birajkarmakar** [comment]
@rtnpro thanks for this idea. I am trying to making like this.

**Comment by darkowlzz** [comment]
Could we have more options ?
I guess we should give it some time before we decide.

**Comment by rtnpro** [comment]
@darkowlzz :+1:  This will indeed take some time. Removing it from 0.1 milestone.

**Comment by rtnpro** [comment]
Just scribbled another concept art for waartaa:

img_20131230_001045

**Comment by darkowlzz** [comment]
Why is the cloud looking so sad?

**Comment by rtnpro** [comment]
@darkowlzz Then make it happy ;)

**Comment by kushaldas** [comment]
Please stop stealing logos. @birajkarmakar did a direct copy from https://twitter.com/cloudapp, that is another reason he did not provide any vector source. Someone should kick his **\* for the same. 
STOP STEALING!!!!

**Comment by sayanchowdhury** [comment]
The inner bubble is also copied from http://goo.gl/uqemDF 
This stock icon is a paid one. This is a completely a design plagiarism.

@birajkarmakar you should start reading about licences. Everything available on internet is not always free and combining two-three icons does not makes you a designer.

**Comment by sayanchowdhury** [comment]
Declining this pull request as it is violating licences.

**Pull request closed without merging**
