### PR TITLE
Updated webpack config and added neccessary packages

### PR DESCRIPTION
**Pull request by sanbornsen**
- Some time npm fails to retrive tags like git+https://github.com/twbs/bootstrap.git#v4.0.0-alpha.2
- ^4.0.0-alpha.2 works perfect instead

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
Can you fix your git config?

**Comment by sanbornsen** [comment]
What's wrong with my git config?

**Comment by sayanchowdhury** [comment]
I am closing this PR. Opening a new one with your changes

**Comment by sanbornsen** [comment]
Okay

**Pull request closed without merging**
